services:
  server:
    build: .
    container_name: team2-server
    ports:
      - "6001:3000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./server.key:/usr/src/app/dist/server.key
      - ./server.crt:/usr/src/app/dist/server.crt
      - ./ca.crt:/usr/src/app/dist/ca.crt

